name: Build and Release convmusic

on:
  push:
    branches:
      - main  # Runs on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Runs on PRs to the 'main' branch

  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        architecture: [x86_64, arm64]
        exclude:
          - os: windows-latest
            architecture: arm64  # Windows ARM builds aren't widely supported

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"  # Adjust as needed

      - name: Install Nuitka
        run: |
          python -m pip install --upgrade pip
          python -m pip install nuitka

      - name: Build with Nuitka
        run: |
          python -m nuitka --standalone --onefile --disable-ccache --output-dir=build convert.py
        shell: bash

      - name: Rename Executable
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mv build/convert.exe build/convmusic.exe
          else
            mv build/convert build/convmusic
            chmod +x build/convmusic
          fi
        shell: bash

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: convmusic-${{ runner.os }}-${{ matrix.architecture }}
          path: |
            build/convmusic*
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
