name: Build Python Executable with Nuitka

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Nuitka
        run: pip install nuitka

      - name: Compile Python script with Nuitka
        run: |
          python -m nuitka --standalone --onefile --output-dir=build convert.py

      - name: Rename output file (without .bin on Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: |
          mv build/convert.bin build/convert

      - name: Rename output file for Windows
        if: matrix.os == 'windows-latest'
        run: |
          rename build\convert.exe convert.exe

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-program-${{ matrix.os }}
          path: build/my_script*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: "Release v1.0.${{ github.run_number }}"
          body: "Automatically built release using Nuitka."
          files: artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
