jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        architecture: [x86_64, arm64]
        exclude:
          - os: windows-latest
            architecture: arm64  # Windows ARM builds aren't well-supported

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build with Nuitka (CI/CD)
        uses: Nuitka/Nuitka-Action@main
        with:
            nuitka-version: main
            script-name: convert.py

      # Rename and upload artifacts based on OS
      - name: Rename and upload macOS Executable
        if: runner.os == 'macOS'
        run: |
          mv build/convert.app/Contents/MacOS/convert build/convert.app/Contents/MacOS/convmusic
        uses: actions/upload-artifact@v4
        with:
          name: convmusic-macos-${{ matrix.architecture }}
          path: build/convmusic.app
          if-no-files-found: error

      - name: Rename and upload Linux Executable
        if: runner.os == 'Linux'
        run: |
          mv build/convert.bin build/convmusic
        uses: actions/upload-artifact@v4
        with:
          name: convmusic-linux-${{ matrix.architecture }}
          path: build/convmusic
          if-no-files-found: error

      - name: Rename and upload Windows Executable
        if: runner.os == 'Windows'
        run: |
          mv build/convert.exe build/convmusic.exe
        uses: actions/upload-artifact@v4
        with:
          name: convmusic-windows-${{ matrix.architecture }}
          path: build/convmusic.exe
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
