name: Build and Release convmusic

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        architecture: [x86_64, arm64]
        exclude:
          - os: windows-latest
            architecture: arm64  # Windows ARM builds aren't well-supported

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Nuitka
        run: |
          python -m pip install --upgrade pip
          python -m pip install nuitka

      - name: Download and Extract Dependency Walker (Windows only)
        if: runner.os == 'Windows'
        run: |
          echo "Downloading Dependency Walker..."
          Invoke-WebRequest -Uri "https://dependencywalker.com/depends22_x64.zip" -OutFile "depends22_x64.zip"
          Expand-Archive -Path "depends22_x64.zip" -DestinationPath "C:\dependency-walker"
          echo "Dependency Walker downloaded and extracted."

      - name: Place Dependency Walker in Nuitka Cache (Windows only)
        if: runner.os == 'Windows'
        run: |
          # Ensure the directory exists
          New-Item -Path "C:\Users\RUNNER~1\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\depends\x86_64" -ItemType Directory -Force
          # Copy Dependency Walker to the required directory
          Copy-Item -Path "C:\dependency-walker\depends.exe" -Destination "C:\Users\RUNNER~1\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\depends\x86_64"
          echo "Dependency Walker placed in the required directory."

      - name: Build on Linux/macOS
        if: runner.os != 'Windows'
        run: chmod +x build.sh && ./build.sh

      - name: Build on Windows
        if: runner.os == 'Windows'
        run: .\build.bat

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: convmusic-${{ runner.os }}-${{ matrix.architecture }}
          path: build/convmusic*
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
