name: Build and Release convmusic

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        architecture: [x86_64, arm64]
        exclude:
          - os: windows-latest
            architecture: arm64  # Windows ARM builds aren't well-supported

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build with Nuitka (CI/CD)
        uses: Nuitka/Nuitka-Action@main
        with:
            nuitka-version: main
            script-name: convert.py

      # macOS Rename and upload
      - name: Rename macOS Executable
        if: runner.os == 'macOS'
        run: |
          mv build/convert.app/Contents/MacOS/convert build/convert.app/Contents/MacOS/convmusic

      - name: Upload macOS Executable
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: convmusic-macos-${{ matrix.architecture }}
          path: build/convert.app/Contents/MacOS/convmusic*  # Corrected path
          if-no-files-found: error

      # Linux Rename and upload
      - name: Rename Linux Executable
        if: runner.os == 'Linux'
        run: |
          mv build/convert.bin build/convmusic

      - name: Upload Linux Executable
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: convmusic-linux-${{ matrix.architecture }}
          path: build/convmusic  # Correct path for Linux
          if-no-files-found: error

      # Windows Rename and upload
      - name: Rename Windows Executable
        if: runner.os == 'Windows'
        run: |
          mv build/convert.exe build/convmusic.exe

      - name: Upload Windows Executable
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: convmusic-windows-${{ matrix.architecture }}
          path: build/convmusic.exe  # Correct path for Windows
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Create GitHub Release
        uses: comnoco/create-release-action@v2.0.5
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - Release V1
          draft: false
          prerelease: false
          files: actions/*/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
